/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalStudentRouteImport } from './routes/portal.student'
import { Route as PortalStaffRouteImport } from './routes/portal.staff'
import { Route as PortalParentRouteImport } from './routes/portal.parent'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as PortalStudentIndexRouteImport } from './routes/portal.student.index'
import { Route as PortalStaffIndexRouteImport } from './routes/portal.staff.index'
import { Route as PortalParentIndexRouteImport } from './routes/portal.parent.index'
import { Route as PortalAdminIndexRouteImport } from './routes/portal.admin.index'
import { Route as PortalStudentResultsRouteImport } from './routes/portal.student.results'
import { Route as PortalStudentProfileRouteImport } from './routes/portal.student.profile'
import { Route as PortalStudentNotificationsRouteImport } from './routes/portal.student.notifications'
import { Route as PortalStudentCbtRouteImport } from './routes/portal.student.cbt'
import { Route as PortalStudentAssignmentsRouteImport } from './routes/portal.student.assignments'
import { Route as PortalStudentAchievementsRouteImport } from './routes/portal.student.achievements'
import { Route as PortalStaffTutorialsRouteImport } from './routes/portal.staff.tutorials'
import { Route as PortalStaffTeachersRouteImport } from './routes/portal.staff.teachers'
import { Route as PortalStaffStudentsRouteImport } from './routes/portal.staff.students'
import { Route as PortalStaffSettingsRouteImport } from './routes/portal.staff.settings'
import { Route as PortalStaffProfileRouteImport } from './routes/portal.staff.profile'
import { Route as PortalStaffPaymentsRouteImport } from './routes/portal.staff.payments'
import { Route as PortalStaffAttendanceRouteImport } from './routes/portal.staff.attendance'
import { Route as PortalStaffAssessmentsRouteImport } from './routes/portal.staff.assessments'
import { Route as PortalStaffAnnouncementsRouteImport } from './routes/portal.staff.announcements'
import { Route as PortalParentProfileRouteImport } from './routes/portal.parent.profile'
import { Route as PortalParentPaymentsRouteImport } from './routes/portal.parent.payments'
import { Route as PortalParentMessagesRouteImport } from './routes/portal.parent.messages'
import { Route as PortalParentAttendanceRouteImport } from './routes/portal.parent.attendance'
import { Route as PortalParentAnnouncementsRouteImport } from './routes/portal.parent.announcements'
import { Route as PortalParentAcademicsRouteImport } from './routes/portal.parent.academics'
import { Route as PortalAdminUsersRouteImport } from './routes/portal.admin.users'
import { Route as PortalAdminSettingsRouteImport } from './routes/portal.admin.settings'
import { Route as PortalAdminSecurityRouteImport } from './routes/portal.admin.security'
import { Route as PortalAdminSchoolsRouteImport } from './routes/portal.admin.schools'
import { Route as PortalAdminReportsRouteImport } from './routes/portal.admin.reports'
import { Route as PortalAdminProfileRouteImport } from './routes/portal.admin.profile'
import { Route as PortalAdminLogsRouteImport } from './routes/portal.admin.logs'
import { Route as PortalAdminFinanceRouteImport } from './routes/portal.admin.finance'
import { Route as PortalAdminClassesRouteImport } from './routes/portal.admin.classes'
import { Route as PortalAdminCbtRouteImport } from './routes/portal.admin.cbt'
import { Route as PortalAdminAuditRouteImport } from './routes/portal.admin.audit'
import { Route as PortalAdminClassesClassIdRouteImport } from './routes/portal.admin.classes.$classId'
import { Route as PortalAdminClassesClassIdStudentsStudentIdRouteImport } from './routes/portal.admin.classes.$classId.students.$studentId'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStudentRoute = PortalStudentRouteImport.update({
  id: '/portal/student',
  path: '/portal/student',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStaffRoute = PortalStaffRouteImport.update({
  id: '/portal/staff',
  path: '/portal/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalParentRoute = PortalParentRouteImport.update({
  id: '/portal/parent',
  path: '/portal/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/portal/admin',
  path: '/portal/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalStudentIndexRoute = PortalStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalStudentRoute,
} as any)
const PortalStaffIndexRoute = PortalStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalParentIndexRoute = PortalParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalParentRoute,
} as any)
const PortalAdminIndexRoute = PortalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalStudentResultsRoute = PortalStudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => PortalStudentRoute,
} as any)
const PortalStudentProfileRoute = PortalStudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalStudentRoute,
} as any)
const PortalStudentNotificationsRoute =
  PortalStudentNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PortalStudentRoute,
  } as any)
const PortalStudentCbtRoute = PortalStudentCbtRouteImport.update({
  id: '/cbt',
  path: '/cbt',
  getParentRoute: () => PortalStudentRoute,
} as any)
const PortalStudentAssignmentsRoute =
  PortalStudentAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => PortalStudentRoute,
  } as any)
const PortalStudentAchievementsRoute =
  PortalStudentAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => PortalStudentRoute,
  } as any)
const PortalStaffTutorialsRoute = PortalStaffTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalStaffTeachersRoute = PortalStaffTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalStaffStudentsRoute = PortalStaffStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalStaffSettingsRoute = PortalStaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalStaffProfileRoute = PortalStaffProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalStaffPaymentsRoute = PortalStaffPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalStaffAttendanceRoute = PortalStaffAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalStaffAssessmentsRoute = PortalStaffAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => PortalStaffRoute,
} as any)
const PortalStaffAnnouncementsRoute =
  PortalStaffAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => PortalStaffRoute,
  } as any)
const PortalParentProfileRoute = PortalParentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalParentRoute,
} as any)
const PortalParentPaymentsRoute = PortalParentPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalParentRoute,
} as any)
const PortalParentMessagesRoute = PortalParentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalParentRoute,
} as any)
const PortalParentAttendanceRoute = PortalParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => PortalParentRoute,
} as any)
const PortalParentAnnouncementsRoute =
  PortalParentAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => PortalParentRoute,
  } as any)
const PortalParentAcademicsRoute = PortalParentAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => PortalParentRoute,
} as any)
const PortalAdminUsersRoute = PortalAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminSettingsRoute = PortalAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminSecurityRoute = PortalAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminSchoolsRoute = PortalAdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminReportsRoute = PortalAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminProfileRoute = PortalAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminLogsRoute = PortalAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminFinanceRoute = PortalAdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminClassesRoute = PortalAdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminCbtRoute = PortalAdminCbtRouteImport.update({
  id: '/cbt',
  path: '/cbt',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminAuditRoute = PortalAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => PortalAdminRoute,
} as any)
const PortalAdminClassesClassIdRoute =
  PortalAdminClassesClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => PortalAdminClassesRoute,
  } as any)
const PortalAdminClassesClassIdStudentsStudentIdRoute =
  PortalAdminClassesClassIdStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => PortalAdminClassesClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/portal/admin': typeof PortalAdminRouteWithChildren
  '/portal/parent': typeof PortalParentRouteWithChildren
  '/portal/staff': typeof PortalStaffRouteWithChildren
  '/portal/student': typeof PortalStudentRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/cbt': typeof PortalAdminCbtRoute
  '/portal/admin/classes': typeof PortalAdminClassesRouteWithChildren
  '/portal/admin/finance': typeof PortalAdminFinanceRoute
  '/portal/admin/logs': typeof PortalAdminLogsRoute
  '/portal/admin/profile': typeof PortalAdminProfileRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/schools': typeof PortalAdminSchoolsRoute
  '/portal/admin/security': typeof PortalAdminSecurityRoute
  '/portal/admin/settings': typeof PortalAdminSettingsRoute
  '/portal/admin/users': typeof PortalAdminUsersRoute
  '/portal/parent/academics': typeof PortalParentAcademicsRoute
  '/portal/parent/announcements': typeof PortalParentAnnouncementsRoute
  '/portal/parent/attendance': typeof PortalParentAttendanceRoute
  '/portal/parent/messages': typeof PortalParentMessagesRoute
  '/portal/parent/payments': typeof PortalParentPaymentsRoute
  '/portal/parent/profile': typeof PortalParentProfileRoute
  '/portal/staff/announcements': typeof PortalStaffAnnouncementsRoute
  '/portal/staff/assessments': typeof PortalStaffAssessmentsRoute
  '/portal/staff/attendance': typeof PortalStaffAttendanceRoute
  '/portal/staff/payments': typeof PortalStaffPaymentsRoute
  '/portal/staff/profile': typeof PortalStaffProfileRoute
  '/portal/staff/settings': typeof PortalStaffSettingsRoute
  '/portal/staff/students': typeof PortalStaffStudentsRoute
  '/portal/staff/teachers': typeof PortalStaffTeachersRoute
  '/portal/staff/tutorials': typeof PortalStaffTutorialsRoute
  '/portal/student/achievements': typeof PortalStudentAchievementsRoute
  '/portal/student/assignments': typeof PortalStudentAssignmentsRoute
  '/portal/student/cbt': typeof PortalStudentCbtRoute
  '/portal/student/notifications': typeof PortalStudentNotificationsRoute
  '/portal/student/profile': typeof PortalStudentProfileRoute
  '/portal/student/results': typeof PortalStudentResultsRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/parent/': typeof PortalParentIndexRoute
  '/portal/staff/': typeof PortalStaffIndexRoute
  '/portal/student/': typeof PortalStudentIndexRoute
  '/portal/admin/classes/$classId': typeof PortalAdminClassesClassIdRouteWithChildren
  '/portal/admin/classes/$classId/students/$studentId': typeof PortalAdminClassesClassIdStudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/portal': typeof PortalIndexRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/cbt': typeof PortalAdminCbtRoute
  '/portal/admin/classes': typeof PortalAdminClassesRouteWithChildren
  '/portal/admin/finance': typeof PortalAdminFinanceRoute
  '/portal/admin/logs': typeof PortalAdminLogsRoute
  '/portal/admin/profile': typeof PortalAdminProfileRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/schools': typeof PortalAdminSchoolsRoute
  '/portal/admin/security': typeof PortalAdminSecurityRoute
  '/portal/admin/settings': typeof PortalAdminSettingsRoute
  '/portal/admin/users': typeof PortalAdminUsersRoute
  '/portal/parent/academics': typeof PortalParentAcademicsRoute
  '/portal/parent/announcements': typeof PortalParentAnnouncementsRoute
  '/portal/parent/attendance': typeof PortalParentAttendanceRoute
  '/portal/parent/messages': typeof PortalParentMessagesRoute
  '/portal/parent/payments': typeof PortalParentPaymentsRoute
  '/portal/parent/profile': typeof PortalParentProfileRoute
  '/portal/staff/announcements': typeof PortalStaffAnnouncementsRoute
  '/portal/staff/assessments': typeof PortalStaffAssessmentsRoute
  '/portal/staff/attendance': typeof PortalStaffAttendanceRoute
  '/portal/staff/payments': typeof PortalStaffPaymentsRoute
  '/portal/staff/profile': typeof PortalStaffProfileRoute
  '/portal/staff/settings': typeof PortalStaffSettingsRoute
  '/portal/staff/students': typeof PortalStaffStudentsRoute
  '/portal/staff/teachers': typeof PortalStaffTeachersRoute
  '/portal/staff/tutorials': typeof PortalStaffTutorialsRoute
  '/portal/student/achievements': typeof PortalStudentAchievementsRoute
  '/portal/student/assignments': typeof PortalStudentAssignmentsRoute
  '/portal/student/cbt': typeof PortalStudentCbtRoute
  '/portal/student/notifications': typeof PortalStudentNotificationsRoute
  '/portal/student/profile': typeof PortalStudentProfileRoute
  '/portal/student/results': typeof PortalStudentResultsRoute
  '/portal/admin': typeof PortalAdminIndexRoute
  '/portal/parent': typeof PortalParentIndexRoute
  '/portal/staff': typeof PortalStaffIndexRoute
  '/portal/student': typeof PortalStudentIndexRoute
  '/portal/admin/classes/$classId': typeof PortalAdminClassesClassIdRouteWithChildren
  '/portal/admin/classes/$classId/students/$studentId': typeof PortalAdminClassesClassIdStudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRoute
  '/portal/admin': typeof PortalAdminRouteWithChildren
  '/portal/parent': typeof PortalParentRouteWithChildren
  '/portal/staff': typeof PortalStaffRouteWithChildren
  '/portal/student': typeof PortalStudentRouteWithChildren
  '/portal/': typeof PortalIndexRoute
  '/portal/admin/audit': typeof PortalAdminAuditRoute
  '/portal/admin/cbt': typeof PortalAdminCbtRoute
  '/portal/admin/classes': typeof PortalAdminClassesRouteWithChildren
  '/portal/admin/finance': typeof PortalAdminFinanceRoute
  '/portal/admin/logs': typeof PortalAdminLogsRoute
  '/portal/admin/profile': typeof PortalAdminProfileRoute
  '/portal/admin/reports': typeof PortalAdminReportsRoute
  '/portal/admin/schools': typeof PortalAdminSchoolsRoute
  '/portal/admin/security': typeof PortalAdminSecurityRoute
  '/portal/admin/settings': typeof PortalAdminSettingsRoute
  '/portal/admin/users': typeof PortalAdminUsersRoute
  '/portal/parent/academics': typeof PortalParentAcademicsRoute
  '/portal/parent/announcements': typeof PortalParentAnnouncementsRoute
  '/portal/parent/attendance': typeof PortalParentAttendanceRoute
  '/portal/parent/messages': typeof PortalParentMessagesRoute
  '/portal/parent/payments': typeof PortalParentPaymentsRoute
  '/portal/parent/profile': typeof PortalParentProfileRoute
  '/portal/staff/announcements': typeof PortalStaffAnnouncementsRoute
  '/portal/staff/assessments': typeof PortalStaffAssessmentsRoute
  '/portal/staff/attendance': typeof PortalStaffAttendanceRoute
  '/portal/staff/payments': typeof PortalStaffPaymentsRoute
  '/portal/staff/profile': typeof PortalStaffProfileRoute
  '/portal/staff/settings': typeof PortalStaffSettingsRoute
  '/portal/staff/students': typeof PortalStaffStudentsRoute
  '/portal/staff/teachers': typeof PortalStaffTeachersRoute
  '/portal/staff/tutorials': typeof PortalStaffTutorialsRoute
  '/portal/student/achievements': typeof PortalStudentAchievementsRoute
  '/portal/student/assignments': typeof PortalStudentAssignmentsRoute
  '/portal/student/cbt': typeof PortalStudentCbtRoute
  '/portal/student/notifications': typeof PortalStudentNotificationsRoute
  '/portal/student/profile': typeof PortalStudentProfileRoute
  '/portal/student/results': typeof PortalStudentResultsRoute
  '/portal/admin/': typeof PortalAdminIndexRoute
  '/portal/parent/': typeof PortalParentIndexRoute
  '/portal/staff/': typeof PortalStaffIndexRoute
  '/portal/student/': typeof PortalStudentIndexRoute
  '/portal/admin/classes/$classId': typeof PortalAdminClassesClassIdRouteWithChildren
  '/portal/admin/classes/$classId/students/$studentId': typeof PortalAdminClassesClassIdStudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/news'
    | '/portal/admin'
    | '/portal/parent'
    | '/portal/staff'
    | '/portal/student'
    | '/portal/'
    | '/portal/admin/audit'
    | '/portal/admin/cbt'
    | '/portal/admin/classes'
    | '/portal/admin/finance'
    | '/portal/admin/logs'
    | '/portal/admin/profile'
    | '/portal/admin/reports'
    | '/portal/admin/schools'
    | '/portal/admin/security'
    | '/portal/admin/settings'
    | '/portal/admin/users'
    | '/portal/parent/academics'
    | '/portal/parent/announcements'
    | '/portal/parent/attendance'
    | '/portal/parent/messages'
    | '/portal/parent/payments'
    | '/portal/parent/profile'
    | '/portal/staff/announcements'
    | '/portal/staff/assessments'
    | '/portal/staff/attendance'
    | '/portal/staff/payments'
    | '/portal/staff/profile'
    | '/portal/staff/settings'
    | '/portal/staff/students'
    | '/portal/staff/teachers'
    | '/portal/staff/tutorials'
    | '/portal/student/achievements'
    | '/portal/student/assignments'
    | '/portal/student/cbt'
    | '/portal/student/notifications'
    | '/portal/student/profile'
    | '/portal/student/results'
    | '/portal/admin/'
    | '/portal/parent/'
    | '/portal/staff/'
    | '/portal/student/'
    | '/portal/admin/classes/$classId'
    | '/portal/admin/classes/$classId/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/news'
    | '/portal'
    | '/portal/admin/audit'
    | '/portal/admin/cbt'
    | '/portal/admin/classes'
    | '/portal/admin/finance'
    | '/portal/admin/logs'
    | '/portal/admin/profile'
    | '/portal/admin/reports'
    | '/portal/admin/schools'
    | '/portal/admin/security'
    | '/portal/admin/settings'
    | '/portal/admin/users'
    | '/portal/parent/academics'
    | '/portal/parent/announcements'
    | '/portal/parent/attendance'
    | '/portal/parent/messages'
    | '/portal/parent/payments'
    | '/portal/parent/profile'
    | '/portal/staff/announcements'
    | '/portal/staff/assessments'
    | '/portal/staff/attendance'
    | '/portal/staff/payments'
    | '/portal/staff/profile'
    | '/portal/staff/settings'
    | '/portal/staff/students'
    | '/portal/staff/teachers'
    | '/portal/staff/tutorials'
    | '/portal/student/achievements'
    | '/portal/student/assignments'
    | '/portal/student/cbt'
    | '/portal/student/notifications'
    | '/portal/student/profile'
    | '/portal/student/results'
    | '/portal/admin'
    | '/portal/parent'
    | '/portal/staff'
    | '/portal/student'
    | '/portal/admin/classes/$classId'
    | '/portal/admin/classes/$classId/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/news'
    | '/portal/admin'
    | '/portal/parent'
    | '/portal/staff'
    | '/portal/student'
    | '/portal/'
    | '/portal/admin/audit'
    | '/portal/admin/cbt'
    | '/portal/admin/classes'
    | '/portal/admin/finance'
    | '/portal/admin/logs'
    | '/portal/admin/profile'
    | '/portal/admin/reports'
    | '/portal/admin/schools'
    | '/portal/admin/security'
    | '/portal/admin/settings'
    | '/portal/admin/users'
    | '/portal/parent/academics'
    | '/portal/parent/announcements'
    | '/portal/parent/attendance'
    | '/portal/parent/messages'
    | '/portal/parent/payments'
    | '/portal/parent/profile'
    | '/portal/staff/announcements'
    | '/portal/staff/assessments'
    | '/portal/staff/attendance'
    | '/portal/staff/payments'
    | '/portal/staff/profile'
    | '/portal/staff/settings'
    | '/portal/staff/students'
    | '/portal/staff/teachers'
    | '/portal/staff/tutorials'
    | '/portal/student/achievements'
    | '/portal/student/assignments'
    | '/portal/student/cbt'
    | '/portal/student/notifications'
    | '/portal/student/profile'
    | '/portal/student/results'
    | '/portal/admin/'
    | '/portal/parent/'
    | '/portal/staff/'
    | '/portal/student/'
    | '/portal/admin/classes/$classId'
    | '/portal/admin/classes/$classId/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRoute
  PortalAdminRoute: typeof PortalAdminRouteWithChildren
  PortalParentRoute: typeof PortalParentRouteWithChildren
  PortalStaffRoute: typeof PortalStaffRouteWithChildren
  PortalStudentRoute: typeof PortalStudentRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/student': {
      id: '/portal/student'
      path: '/portal/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof PortalStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/staff': {
      id: '/portal/staff'
      path: '/portal/staff'
      fullPath: '/portal/staff'
      preLoaderRoute: typeof PortalStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/parent': {
      id: '/portal/parent'
      path: '/portal/parent'
      fullPath: '/portal/parent'
      preLoaderRoute: typeof PortalParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/student/': {
      id: '/portal/student/'
      path: '/'
      fullPath: '/portal/student/'
      preLoaderRoute: typeof PortalStudentIndexRouteImport
      parentRoute: typeof PortalStudentRoute
    }
    '/portal/staff/': {
      id: '/portal/staff/'
      path: '/'
      fullPath: '/portal/staff/'
      preLoaderRoute: typeof PortalStaffIndexRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/parent/': {
      id: '/portal/parent/'
      path: '/'
      fullPath: '/portal/parent/'
      preLoaderRoute: typeof PortalParentIndexRouteImport
      parentRoute: typeof PortalParentRoute
    }
    '/portal/admin/': {
      id: '/portal/admin/'
      path: '/'
      fullPath: '/portal/admin/'
      preLoaderRoute: typeof PortalAdminIndexRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/student/results': {
      id: '/portal/student/results'
      path: '/results'
      fullPath: '/portal/student/results'
      preLoaderRoute: typeof PortalStudentResultsRouteImport
      parentRoute: typeof PortalStudentRoute
    }
    '/portal/student/profile': {
      id: '/portal/student/profile'
      path: '/profile'
      fullPath: '/portal/student/profile'
      preLoaderRoute: typeof PortalStudentProfileRouteImport
      parentRoute: typeof PortalStudentRoute
    }
    '/portal/student/notifications': {
      id: '/portal/student/notifications'
      path: '/notifications'
      fullPath: '/portal/student/notifications'
      preLoaderRoute: typeof PortalStudentNotificationsRouteImport
      parentRoute: typeof PortalStudentRoute
    }
    '/portal/student/cbt': {
      id: '/portal/student/cbt'
      path: '/cbt'
      fullPath: '/portal/student/cbt'
      preLoaderRoute: typeof PortalStudentCbtRouteImport
      parentRoute: typeof PortalStudentRoute
    }
    '/portal/student/assignments': {
      id: '/portal/student/assignments'
      path: '/assignments'
      fullPath: '/portal/student/assignments'
      preLoaderRoute: typeof PortalStudentAssignmentsRouteImport
      parentRoute: typeof PortalStudentRoute
    }
    '/portal/student/achievements': {
      id: '/portal/student/achievements'
      path: '/achievements'
      fullPath: '/portal/student/achievements'
      preLoaderRoute: typeof PortalStudentAchievementsRouteImport
      parentRoute: typeof PortalStudentRoute
    }
    '/portal/staff/tutorials': {
      id: '/portal/staff/tutorials'
      path: '/tutorials'
      fullPath: '/portal/staff/tutorials'
      preLoaderRoute: typeof PortalStaffTutorialsRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/staff/teachers': {
      id: '/portal/staff/teachers'
      path: '/teachers'
      fullPath: '/portal/staff/teachers'
      preLoaderRoute: typeof PortalStaffTeachersRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/staff/students': {
      id: '/portal/staff/students'
      path: '/students'
      fullPath: '/portal/staff/students'
      preLoaderRoute: typeof PortalStaffStudentsRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/staff/settings': {
      id: '/portal/staff/settings'
      path: '/settings'
      fullPath: '/portal/staff/settings'
      preLoaderRoute: typeof PortalStaffSettingsRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/staff/profile': {
      id: '/portal/staff/profile'
      path: '/profile'
      fullPath: '/portal/staff/profile'
      preLoaderRoute: typeof PortalStaffProfileRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/staff/payments': {
      id: '/portal/staff/payments'
      path: '/payments'
      fullPath: '/portal/staff/payments'
      preLoaderRoute: typeof PortalStaffPaymentsRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/staff/attendance': {
      id: '/portal/staff/attendance'
      path: '/attendance'
      fullPath: '/portal/staff/attendance'
      preLoaderRoute: typeof PortalStaffAttendanceRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/staff/assessments': {
      id: '/portal/staff/assessments'
      path: '/assessments'
      fullPath: '/portal/staff/assessments'
      preLoaderRoute: typeof PortalStaffAssessmentsRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/staff/announcements': {
      id: '/portal/staff/announcements'
      path: '/announcements'
      fullPath: '/portal/staff/announcements'
      preLoaderRoute: typeof PortalStaffAnnouncementsRouteImport
      parentRoute: typeof PortalStaffRoute
    }
    '/portal/parent/profile': {
      id: '/portal/parent/profile'
      path: '/profile'
      fullPath: '/portal/parent/profile'
      preLoaderRoute: typeof PortalParentProfileRouteImport
      parentRoute: typeof PortalParentRoute
    }
    '/portal/parent/payments': {
      id: '/portal/parent/payments'
      path: '/payments'
      fullPath: '/portal/parent/payments'
      preLoaderRoute: typeof PortalParentPaymentsRouteImport
      parentRoute: typeof PortalParentRoute
    }
    '/portal/parent/messages': {
      id: '/portal/parent/messages'
      path: '/messages'
      fullPath: '/portal/parent/messages'
      preLoaderRoute: typeof PortalParentMessagesRouteImport
      parentRoute: typeof PortalParentRoute
    }
    '/portal/parent/attendance': {
      id: '/portal/parent/attendance'
      path: '/attendance'
      fullPath: '/portal/parent/attendance'
      preLoaderRoute: typeof PortalParentAttendanceRouteImport
      parentRoute: typeof PortalParentRoute
    }
    '/portal/parent/announcements': {
      id: '/portal/parent/announcements'
      path: '/announcements'
      fullPath: '/portal/parent/announcements'
      preLoaderRoute: typeof PortalParentAnnouncementsRouteImport
      parentRoute: typeof PortalParentRoute
    }
    '/portal/parent/academics': {
      id: '/portal/parent/academics'
      path: '/academics'
      fullPath: '/portal/parent/academics'
      preLoaderRoute: typeof PortalParentAcademicsRouteImport
      parentRoute: typeof PortalParentRoute
    }
    '/portal/admin/users': {
      id: '/portal/admin/users'
      path: '/users'
      fullPath: '/portal/admin/users'
      preLoaderRoute: typeof PortalAdminUsersRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/settings': {
      id: '/portal/admin/settings'
      path: '/settings'
      fullPath: '/portal/admin/settings'
      preLoaderRoute: typeof PortalAdminSettingsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/security': {
      id: '/portal/admin/security'
      path: '/security'
      fullPath: '/portal/admin/security'
      preLoaderRoute: typeof PortalAdminSecurityRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/schools': {
      id: '/portal/admin/schools'
      path: '/schools'
      fullPath: '/portal/admin/schools'
      preLoaderRoute: typeof PortalAdminSchoolsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/reports': {
      id: '/portal/admin/reports'
      path: '/reports'
      fullPath: '/portal/admin/reports'
      preLoaderRoute: typeof PortalAdminReportsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/profile': {
      id: '/portal/admin/profile'
      path: '/profile'
      fullPath: '/portal/admin/profile'
      preLoaderRoute: typeof PortalAdminProfileRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/logs': {
      id: '/portal/admin/logs'
      path: '/logs'
      fullPath: '/portal/admin/logs'
      preLoaderRoute: typeof PortalAdminLogsRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/finance': {
      id: '/portal/admin/finance'
      path: '/finance'
      fullPath: '/portal/admin/finance'
      preLoaderRoute: typeof PortalAdminFinanceRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/classes': {
      id: '/portal/admin/classes'
      path: '/classes'
      fullPath: '/portal/admin/classes'
      preLoaderRoute: typeof PortalAdminClassesRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/cbt': {
      id: '/portal/admin/cbt'
      path: '/cbt'
      fullPath: '/portal/admin/cbt'
      preLoaderRoute: typeof PortalAdminCbtRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/audit': {
      id: '/portal/admin/audit'
      path: '/audit'
      fullPath: '/portal/admin/audit'
      preLoaderRoute: typeof PortalAdminAuditRouteImport
      parentRoute: typeof PortalAdminRoute
    }
    '/portal/admin/classes/$classId': {
      id: '/portal/admin/classes/$classId'
      path: '/$classId'
      fullPath: '/portal/admin/classes/$classId'
      preLoaderRoute: typeof PortalAdminClassesClassIdRouteImport
      parentRoute: typeof PortalAdminClassesRoute
    }
    '/portal/admin/classes/$classId/students/$studentId': {
      id: '/portal/admin/classes/$classId/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/portal/admin/classes/$classId/students/$studentId'
      preLoaderRoute: typeof PortalAdminClassesClassIdStudentsStudentIdRouteImport
      parentRoute: typeof PortalAdminClassesClassIdRoute
    }
  }
}

interface PortalAdminClassesClassIdRouteChildren {
  PortalAdminClassesClassIdStudentsStudentIdRoute: typeof PortalAdminClassesClassIdStudentsStudentIdRoute
}

const PortalAdminClassesClassIdRouteChildren: PortalAdminClassesClassIdRouteChildren =
  {
    PortalAdminClassesClassIdStudentsStudentIdRoute:
      PortalAdminClassesClassIdStudentsStudentIdRoute,
  }

const PortalAdminClassesClassIdRouteWithChildren =
  PortalAdminClassesClassIdRoute._addFileChildren(
    PortalAdminClassesClassIdRouteChildren,
  )

interface PortalAdminClassesRouteChildren {
  PortalAdminClassesClassIdRoute: typeof PortalAdminClassesClassIdRouteWithChildren
}

const PortalAdminClassesRouteChildren: PortalAdminClassesRouteChildren = {
  PortalAdminClassesClassIdRoute: PortalAdminClassesClassIdRouteWithChildren,
}

const PortalAdminClassesRouteWithChildren =
  PortalAdminClassesRoute._addFileChildren(PortalAdminClassesRouteChildren)

interface PortalAdminRouteChildren {
  PortalAdminAuditRoute: typeof PortalAdminAuditRoute
  PortalAdminCbtRoute: typeof PortalAdminCbtRoute
  PortalAdminClassesRoute: typeof PortalAdminClassesRouteWithChildren
  PortalAdminFinanceRoute: typeof PortalAdminFinanceRoute
  PortalAdminLogsRoute: typeof PortalAdminLogsRoute
  PortalAdminProfileRoute: typeof PortalAdminProfileRoute
  PortalAdminReportsRoute: typeof PortalAdminReportsRoute
  PortalAdminSchoolsRoute: typeof PortalAdminSchoolsRoute
  PortalAdminSecurityRoute: typeof PortalAdminSecurityRoute
  PortalAdminSettingsRoute: typeof PortalAdminSettingsRoute
  PortalAdminUsersRoute: typeof PortalAdminUsersRoute
  PortalAdminIndexRoute: typeof PortalAdminIndexRoute
}

const PortalAdminRouteChildren: PortalAdminRouteChildren = {
  PortalAdminAuditRoute: PortalAdminAuditRoute,
  PortalAdminCbtRoute: PortalAdminCbtRoute,
  PortalAdminClassesRoute: PortalAdminClassesRouteWithChildren,
  PortalAdminFinanceRoute: PortalAdminFinanceRoute,
  PortalAdminLogsRoute: PortalAdminLogsRoute,
  PortalAdminProfileRoute: PortalAdminProfileRoute,
  PortalAdminReportsRoute: PortalAdminReportsRoute,
  PortalAdminSchoolsRoute: PortalAdminSchoolsRoute,
  PortalAdminSecurityRoute: PortalAdminSecurityRoute,
  PortalAdminSettingsRoute: PortalAdminSettingsRoute,
  PortalAdminUsersRoute: PortalAdminUsersRoute,
  PortalAdminIndexRoute: PortalAdminIndexRoute,
}

const PortalAdminRouteWithChildren = PortalAdminRoute._addFileChildren(
  PortalAdminRouteChildren,
)

interface PortalParentRouteChildren {
  PortalParentAcademicsRoute: typeof PortalParentAcademicsRoute
  PortalParentAnnouncementsRoute: typeof PortalParentAnnouncementsRoute
  PortalParentAttendanceRoute: typeof PortalParentAttendanceRoute
  PortalParentMessagesRoute: typeof PortalParentMessagesRoute
  PortalParentPaymentsRoute: typeof PortalParentPaymentsRoute
  PortalParentProfileRoute: typeof PortalParentProfileRoute
  PortalParentIndexRoute: typeof PortalParentIndexRoute
}

const PortalParentRouteChildren: PortalParentRouteChildren = {
  PortalParentAcademicsRoute: PortalParentAcademicsRoute,
  PortalParentAnnouncementsRoute: PortalParentAnnouncementsRoute,
  PortalParentAttendanceRoute: PortalParentAttendanceRoute,
  PortalParentMessagesRoute: PortalParentMessagesRoute,
  PortalParentPaymentsRoute: PortalParentPaymentsRoute,
  PortalParentProfileRoute: PortalParentProfileRoute,
  PortalParentIndexRoute: PortalParentIndexRoute,
}

const PortalParentRouteWithChildren = PortalParentRoute._addFileChildren(
  PortalParentRouteChildren,
)

interface PortalStaffRouteChildren {
  PortalStaffAnnouncementsRoute: typeof PortalStaffAnnouncementsRoute
  PortalStaffAssessmentsRoute: typeof PortalStaffAssessmentsRoute
  PortalStaffAttendanceRoute: typeof PortalStaffAttendanceRoute
  PortalStaffPaymentsRoute: typeof PortalStaffPaymentsRoute
  PortalStaffProfileRoute: typeof PortalStaffProfileRoute
  PortalStaffSettingsRoute: typeof PortalStaffSettingsRoute
  PortalStaffStudentsRoute: typeof PortalStaffStudentsRoute
  PortalStaffTeachersRoute: typeof PortalStaffTeachersRoute
  PortalStaffTutorialsRoute: typeof PortalStaffTutorialsRoute
  PortalStaffIndexRoute: typeof PortalStaffIndexRoute
}

const PortalStaffRouteChildren: PortalStaffRouteChildren = {
  PortalStaffAnnouncementsRoute: PortalStaffAnnouncementsRoute,
  PortalStaffAssessmentsRoute: PortalStaffAssessmentsRoute,
  PortalStaffAttendanceRoute: PortalStaffAttendanceRoute,
  PortalStaffPaymentsRoute: PortalStaffPaymentsRoute,
  PortalStaffProfileRoute: PortalStaffProfileRoute,
  PortalStaffSettingsRoute: PortalStaffSettingsRoute,
  PortalStaffStudentsRoute: PortalStaffStudentsRoute,
  PortalStaffTeachersRoute: PortalStaffTeachersRoute,
  PortalStaffTutorialsRoute: PortalStaffTutorialsRoute,
  PortalStaffIndexRoute: PortalStaffIndexRoute,
}

const PortalStaffRouteWithChildren = PortalStaffRoute._addFileChildren(
  PortalStaffRouteChildren,
)

interface PortalStudentRouteChildren {
  PortalStudentAchievementsRoute: typeof PortalStudentAchievementsRoute
  PortalStudentAssignmentsRoute: typeof PortalStudentAssignmentsRoute
  PortalStudentCbtRoute: typeof PortalStudentCbtRoute
  PortalStudentNotificationsRoute: typeof PortalStudentNotificationsRoute
  PortalStudentProfileRoute: typeof PortalStudentProfileRoute
  PortalStudentResultsRoute: typeof PortalStudentResultsRoute
  PortalStudentIndexRoute: typeof PortalStudentIndexRoute
}

const PortalStudentRouteChildren: PortalStudentRouteChildren = {
  PortalStudentAchievementsRoute: PortalStudentAchievementsRoute,
  PortalStudentAssignmentsRoute: PortalStudentAssignmentsRoute,
  PortalStudentCbtRoute: PortalStudentCbtRoute,
  PortalStudentNotificationsRoute: PortalStudentNotificationsRoute,
  PortalStudentProfileRoute: PortalStudentProfileRoute,
  PortalStudentResultsRoute: PortalStudentResultsRoute,
  PortalStudentIndexRoute: PortalStudentIndexRoute,
}

const PortalStudentRouteWithChildren = PortalStudentRoute._addFileChildren(
  PortalStudentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRoute,
  PortalAdminRoute: PortalAdminRouteWithChildren,
  PortalParentRoute: PortalParentRouteWithChildren,
  PortalStaffRoute: PortalStaffRouteWithChildren,
  PortalStudentRoute: PortalStudentRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
